export const products = [
    { id: 1, name: "Headphone Black V100", img: "src/images/phone1.jpg", price: 150.99, type: "semFio", marca: "Zoe", date: new Date("2022-09-21"), color: "escura", modality: "", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 2, name: "Headphone Red Y25", img: "src/images/phone2.jpg", price: 250.99, type: "comFio", marca: "Zoe", date: new Date("2022-07-11"), color: "escura", modality: "", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 3, name: "Headphone Pink Soft V100", img: "src/images/phone3.jpg", price: 190.00, type: "comFio", marca: "Elektra", date: new Date("2023-01-25"), color: "clara", modality: "frete", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 4, name: "Headphone White T70", img: "src/images/phone4.jpg", price: 100.00, type: "semFio", marca: "Elektra", date: new Date("2023-01-14"), color: "clara", modality: "frete", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 5, name: "Earphone White X20", img: "src/images/phone5.jpg", price: 20.99, type: "comFio", marca: "Zoe", date: new Date("2022-01-31"), color: "clara", modality: "", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 6, name: "Headphone Blue XX201", img: "src/images/phone6.jpg", price: 220.00, type: "comFio", marca: "Elektra", date: new Date("2023-02-05"), color: "escura", modality: "frete", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 7, name: "Headphone White T80", img: "src/images/phone7.jpg", price: 100.00, type: "comFio", marca: "Elektra", date: new Date("2023-02-05"), color: "clara", modality: "frete", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 8, name: "Headphone Black C40", img: "src/images/phone8.jpg", price: 180.99, type: "semFio", marca: "Zoe", date: new Date("2022-11-10"), color: "escura", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 9, name: "Earphone White L30", img: "src/images/phone9.jpg", price: 15.99, type: "comFio", marca: "Elektra", date: new Date("2022-11-02"), color: "clara", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 10, name: "Headphone Silver R600", img: "src/images/phone10.jpg", price: 230.99, type: "semFio", marca: "Zoe", date: new Date("2023-01-08"), color: "clara", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 11, name: "Headphone Gold E100", img: "src/images/phone11.jpg", price: 190.99, type: "semFio", marca: "Elektra", date: new Date("2022-02-25"), color: "clara", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 12, name: "Headphone Green Military J100", img: "src/images/phone12.jpg", price: 300.99, type: "semFio", marca: "Zoe", date: new Date("2022-12-08"), color: "escura", modality: "frete", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 13, name: "Earphone Black O8", img: "src/images/phone13.jpg", price: 90.00, type: "semFio", marca: "Elektra", date: new Date("2022-12-08"), color: "escura", modality: "", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 14, name: "Earphone White K50", img: "src/images/phone14.jpg", price: 50.99, type: "semFio", marca: "Zoe", date: new Date("2022-05-07"), color: "clara", modality: "", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 15, name: "Earphone White P8", img: "src/images/phone15.jpg", price: 80.99, type: "semFio", marca: "Elektra", date: new Date("2022-11-23"), color: "clara", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" },
    { id: 16, name: "Earphone White U20", img: "src/images/phone16.jpg", price: 50.99, type: "semFio", marca: "Zoe", date: new Date("2022-08-28"), color: "clara", modality: "kit", description: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ipsum, quidem?" }
];

